version: "3"
services:
  gpt2:
    name: janken-tf
    build: tensorflow/tensorflow:latest-gpu
    volumes:
      - ../:/code
    tty: true
    stdin_open: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: /bin/bash