version: "3"
services:
  gpt2:
    name: torch
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/code
    tty: true
    stdin_open: true
    ipc: host
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    command: /bin/bash